### ISSUE TITLE
RuntimeError: shape '[1, 2048, 10, 10]' is invalid for input of size 2048

### ISSUE THREAD

**Issue by lisafjellstrom** [moboehle/Pytorch-LRP#12]
I'm trying to analyze FaceForensics detector [XceptionNet](https://github.com/ondyari/FaceForensics/tree/master/classification) with your LRP implementation, but I get stuck when trying to analyze the first Conv2d layer (the last conv in the network) in the backpass. I'm getting this error message when trying to reshape relevance_in in method conv_nd_inverse (file: inverter_util.py):

relevance_in = relevance_in.view(m.out_shape)
RuntimeError: shape '[1, 2048, 10, 10]' is invalid for input of size 2048

So relevance_in has size torch.Size([1, 2048]) and m.out_shape is [1, 2048, 10, 10]. Why am I getting this error?

**Comment by loukasilias** [comment]
Hi,

I am getting the same error.
did you fix it?
