### ISSUE TITLE
NameError: name 'INSERT' is not defined

### ISSUE THREAD

**Issue by Yung-zi** [moboehle/Pytorch-LRP#15]
When I tried to run this code in colab notebook , it occured the problem as "NameError: name 'INSERT' is not defined" during the process of importing setting.py.  I wonder the reason behind it because I couldn't find corresponding useful information on the Internet. Thanks.

**Comment by joseed-europeana** [comment]
You can define a variable INSERT = '' at settings.py to get rid of the error. It is not necessary for running the MNIST example notebook

**Comment by YH2010** [comment]
The error  "NameError: name 'INSERT' is not defined" occur when running the MNIST example notebook with docker. How to set it? Thanks a lot.

**Comment by YH2010** [comment]
Could you please introduce the process of converting from Raw data to HDF5 file? Thank you.

**Comment by derEitel** [comment]
> Could you please introduce the process of converting from Raw data to HDF5 file? Thank you.

You can find code for this here:
https://github.com/moboehle/Pytorch-LRP/blob/master/Data%20Split%20ADNI.ipynb
