### ISSUE TITLE
How to get "holdout_AD_CN_2Yr15T_plus_UniqueScreening_ID_Hippocampus.h5"

### ISSUE THREAD

**Issue by YH2010** [moboehle/Pytorch-LRP#16]
Could you please supply some detail on how to get the "holdout_AD_CN_2Yr15T_plus_UniqueScreening_ID_Hippocampus.h5" file, which is in "Beta Correlation.ipynb" script? Thank you very much.

**Comment by derEitel** [comment]
The ADNIMerge table has a column that contains the hippocampus volume. You can store that into an HDF5 file or simple read it from the table, making sure that you match your patient IDs.
