### ISSUE TITLE
Version of Pytorch and Python

### ISSUE THREAD

**Issue by avisekiit** [moboehle/Pytorch-LRP#6]
Hi,

Thanks for the awesome repo. However, I am getting some syntax errors and I guess it might be due to difference of your Pytorch and Python. Can you kindly comment on

1. Version of Pytorch
2. Version of Python

For example I am getting 'syntax error' in the following line:
https://github.com/moboehle/Pytorch-LRP/blob/master/inverter_util.py#L207

Keenly looking forward to your response.

Thanks,
Avisek

**Comment by derEitel** [comment]
Hi Avisek,

PyTorch version used:  '1.0.0'
Python version used: 3.6

Hope that helps!
Best,
Fabian
